source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.1'
gem 'puma', '~> 6.0'
gem 'redis', '~> 5.0'

# JSON serialization
gem 'oj', '~> 3.16'

# CORS
gem 'rack-cors', '~> 2.0'

group :development, :test do
  gem 'debug'
  gem 'rspec-rails', '~> 6.1'
end

group :test do
  gem 'factory_bot_rails'
  gem 'shoulda-matchers'
end
